require('dotenv').config();
const fs = require('fs');

const key = process.env.GROQ_API_KEY || '';
if (!key) {
  console.warn('⚠️  GROQ_API_KEY not found in .env');
}

const content = `// Auto-generated by generate-config.js — DO NOT commit this file
window.ENV = {
  GROQ_API_KEY: '${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}'
};
`;

fs.writeFileSync('./config.js', content);
console.log('✅ config.js generated successfully.');
